### ISSUE TITLE
pod install not working

### ISSUE THREAD

**Issue by abhilashdonepudi** [mopinion/mopinion-sdk-ios#1]
Team,

We tried to install the pod and we are getting the following error. Could you please help us with this issue ?

Analyzing dependencies
Pre-downloading: `DoubleConversion` from `git@github.com:mopinion/mopinion-sdk-ios.git`
The authenticity of host 'github.com (193.31.251.102)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes

[!] Error installing DoubleConversion
[!] Failed to download 'DoubleConversion'.

**Comment by mopinion** [comment]
Hi,

thanks for your feedback.
We can't reproduce this issue and we haven't heard it before.
In the message it seems you have problems with your SSH key on Github.

You could try to use the http link in your Podfile: 

`https://github.com/mopinion/mopinion-sdk-ios.git`
instead of `git@github.com:mopinion/mopinion-sdk-ios.git`

This article could also be helpful:
[https://help.github.com/en/articles/testing-your-ssh-connection](https://help.github.com/en/articles/testing-your-ssh-connection)

**Comment by vikdenic** [comment]
> Team,
> 
> We tried to install the pod and we are getting the following error. Could you please help us with this issue ?
> 
> Analyzing dependencies
> Pre-downloading: `DoubleConversion` from `git@github.com:mopinion/mopinion-sdk-ios.git`
> The authenticity of host 'github.com (193.31.251.102)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no)? yes
> 
> [!] Error installing DoubleConversion
> [!] Failed to download 'DoubleConversion'.

I know this is closed but I've run into the same issue.
