### ISSUE TITLE
Only get message "No form opened" while using SDK

### ISSUE THREAD

**Issue by puelocesar** [mopinion/mopinion-sdk-ios#3]
I'm following all the instructions on how to integrate the framework into my demo Swift project but the form is not showing up:

```
[Mopinion SDK 0.4.3 log]>  event "_button" sent
[Mopinion SDK 0.4.3 log]>  Opening Mopinion form...
[Mopinion SDK 0.4.3 log]>  check API
[Mopinion SDK 0.4.3 log]>  Requesting data from https://mjolnir.mopinion.com/pastease/mobile/w7dyrtxq969imtjr30jpgiun5f0v3f0hfjw
[Mopinion SDK 0.4.3 log]>  OK!
[Mopinion SDK 0.4.3 log]>  deployment from API
[Mopinion SDK 0.4.3 log]>  server side check, NO
[Mopinion SDK 0.4.3 log]>  rule triggers: (
)
[Mopinion SDK 0.4.3 log]>  event: _button
[Mopinion SDK 0.4.3 log]>  No form opened
```

**Comment by GustaafL** [comment]
Hi,

The form can not be found because the deployment that is fetched at "https://mjolnir.mopinion.com/pastease/mobile/w7dyrtxq969imtjr30jpgiun5f0v3f0hfjw" is a web deplyment. To use the SDK an in-app deployment has to be used. The in-app deployment is not available in the default trial. Please contact us at support@mopinion.com to get an upgraded trial.
